### ISSUE TITLE
grasshopper-admin install fails on Windows 10

### ISSUE THREAD

**Issue by ChicagoDave** [Solid-Interactive/grasshopper-cli#20]
Not really any information to go on...

```
Automated Grasshopper setup. A fresh Grasshopper application will be created in this directory.
To ensure that this process goes smoothly please review the prerequisites: https://github.com/Solid-Interactive/grasshopper-cli

[?] Do you want to continue? Yes


Creating project scaffolding...

Making directories [Complete]

RUNNING: npm install grasshopper-api --save

Installing grasshopper-api [Complete]

RUNNING: npm install grasshopper-admin --save

Installing grasshopper-admin [Complete]

RUNNING: npm install express --save

Installing express [Complete]

RUNNING: npm install jade --save

Installing jade [Complete]

RUNNING: D:\Dropbox\projects\gh\node_modules\.bin\grasshopper build

Building grasshopper-admin. Please wait, this can take a few minutes. ･･●･･exec error: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "D:\Dropbox\projects\gh\node_modules\.bin\grasshopper build"



Setup failed!

Reason: 3
```

**Comment by travism** [comment]
Did you try the troubleshooting commands from the readme? 
https://github.com/Solid-Interactive/grasshopper-cli#troubleshooting

It looks like it had an issue compiling the admin interface. If you try compiling the admin on it's own some more helpful errors will probably be thrown. 

Try this (just the windows way):

```
<prompt> ./node_modules/.bin/grasshopper build
```

**Comment by travism** [comment]
If you capture the output and there is an error that is not a missing dependency please post your terminal output.

**Comment by SakethVerma** [comment]
E:\project\myproject\node_modules\grasshopper-admin\bin\gha:8
process.chdir(path.normalize('node_modules/grasshopper-admin'));
        ^

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at Object.<anonymous> (E:\project\myproject\node_modules\grasshopper-admin\bin\gha:8:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3


This is the output I captured from cmd

**Comment by kadosh1000** [comment]
Did you solve it out? I am having the exact same problem

**Comment by travism** [comment]
We will try it out on windows and verify the issue.

On Sun, Mar 6, 2016 at 5:49 AM, kadosh1000 <notifications@github.com> wrote:

> Did you solve it out? I am having the exact same problem
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Solid-Interactive/grasshopper-cli/issues/20#issuecomment-192890976>
> .
>



-- 

*Travis McHattie*
Chief Operating Officer
877-899-9981 x201 | Skype: travis.com


thinksolid.com | @thinksolid

**Comment by travism** [comment]
There was definitely some path issues (file escaping) on windows, I did a sweep to fix them. Successfully ran grasshopper fly and launched a site on windows 10. 

Closing.

**Comment by travism** [comment]
To verify you can run npm update -g grasshopper-cli on an existing installation
